### PR TITLE
Create Key takeaways for hiring developers.md

### PR DESCRIPTION
**Pull request by jlius3r**
Hi team, just created a new file that details the main takeaways for sourcing, attracting, and retaining developer talent. Included is a link to infoworld, which lists 7 rules, as well as an image that I think is funny. Your feedback is greatly appreciated!

### CODE REVIEW

**Comment by jlius3r** [comment]
@ToryTCBS @djohnson32 @rgc2127 @nmehta16 Sorry guys, I made a mistake on my previous pull request. Can I get your feedback here? Thanks!

**Comment by djohnson32** [comment]
Please enter a large title to make the page more readable

**Comment by jlius3r** [comment]
Thank you both for the feedback! Your comments have been integrated into my file. Please review again and give me the "ready to ship" signal!

**Comment by nmehta16** [comment]
:+1: to :ship:

**Comment by djohnson32** [comment]
LGTM

**Comment by rgc2127** [comment]
:+1:

**Pull request merged**
