### PR TITLE
Create managing-software-development.md

### PR DESCRIPTION
**Pull request by ToryTCBS**
Take a look guys!

### CODE REVIEW

**Comment by jlius3r** [comment]
@ToryTCBS Tory, please, fix that image asap.

**Comment by nmehta16** [comment]
@ToryTCBS can you move the URL to the top so it's more visible to readers?

**Comment by rgc2127** [comment]
Please eliminate the last exclamation point and replace it with a "."  I prefer sentences to end with periods. Thanks!

**Comment by ToryTCBS** [comment]
@rgc2127 Got it! I think we're all set now.

**Pull request merged**
