### PR TITLE
Reducing software entropy

### PR DESCRIPTION
**Pull request by djohnson32**

### CODE REVIEW

**Comment by jlius3r** [comment]
@djohnson32 Hey David, did you fix that link yet?

**Comment by nmehta16** [comment]
You explained this nicely. Is there any more information out there to help me understand more?

**Comment by ToryTCBS** [comment]
Hi David, can you just add a space before the parentheses? Thanks!

**Comment by djohnson32** [comment]
Is this ready to ship?

**Comment by nmehta16** [comment]
:+1: to :ship:

**Comment by rgc2127** [comment]
Looks like :hankey:

**Comment by djohnson32** [comment]
What would make it look better?

**Comment by rgc2127** [comment]
Eliminate the extra space between before the wikipedia link and then add it back again.  then it will look :gem: :dollar: :moneybag:

**Comment by rgc2127** [comment]
Add a horizontal breaker before the links

**Comment by djohnson32** [comment]
Done!

**Pull request merged**
