### PR TITLE
Create website-or-app.md

### PR DESCRIPTION
**Pull request by nmehta16**
Hi team,

Here's some info that I think would be useful for first timers deciding on whether to build a website or an app. It lists some of the benefits of websites and also provides external sources for more information.

Thanks!

### CODE REVIEW

**Comment by djohnson32** [comment]
I believe the line "A website has more reach and takes less effort to create" should be a bullet point.

**Comment by nmehta16** [comment]
@ToryTCBS @jlius3r @djohnson32 @rgc2127 
Is this good to ship?

**Comment by jlius3r** [comment]
@nmehta16 :+1 to :ship:

**Comment by jlius3r** [comment]
@nmehta16 :+1:

**Comment by djohnson32** [comment]
LGTM

**Comment by rgc2127** [comment]
:+1:

**Pull request merged**
